# Branches that trigger a build on commit
trigger:
- master
- master-vs-deps
- release/*
- features/*
- demos/*

# Branches that trigger builds on PR
pr:
- master
- master-vs-deps
- release/*
- features/*
- demos/*

stages:

- stage: Stage_1
  dependsOn: []
  jobs:
  - job: Say_Hello
    pool:
      vmImage: windows-2019
    steps:
    - checkout: none
    - pwsh: echo 'Hello Stage_1'
  - job: Get_Nonexistent_Item
    dependsOn: Say_Hello
    pool:
      vmImage: windows-2019
    steps:
    - checkout: none
    - pwsh: gi nonexistent1.txt

- stage: Stage_2
  dependsOn: []
  jobs:
  - job: Say_How_Are_You
    pool:
      vmImage: windows-2019
    steps:
    - checkout: none
    - pwsh: echo 'Hello Stage_2'
  - job: Get_Nonexistent_Item
    dependsOn: Say_How_Are_You
    pool:
      vmImage: windows-2019
    steps:
    - checkout: none
    - pwsh: gi nonexistent2.txt

  # - job: List_Roslyn_PRs
  #   pool: server
  #   steps:
  #   - task: InvokeRESTAPI@1
  #     inputs:
  #       connectionType: 'connectedServiceName'
  #       serviceConnection: 'dotnet'
  #       method: 'GET'
  #       urlSuffix: /pulls
  #       waitForCompletion: false
  #       header: '{}'