# Branches that trigger a build on commit
trigger:
- master
- master-vs-deps
- release/*
- features/*
- demos/*

# Branches that trigger builds on PR
pr:
- master
- master-vs-deps
- release/*
- features/*
- demos/*

stages:
- template: eng/pipelines/build-windows-job.yml
  parameters:
    jobName: Build_Windows_Debug
    testArtifactName: Transport_Artifacts_Windows_Debug
    configuration: Debug
    queueName: BuildPool.Windows.10.Amd64.Open
- template: eng/pipelines/test-windows-job.yml
  parameters:
    testRunName: 'Test Windows CoreClr Debug'
    jobName: Test_Windows_CoreClr_Debug
    buildJobName: Build_Windows_Debug
    testArtifactName: Transport_Artifacts_Windows_Debug
    configuration: Debug
    testArguments: -testCoreClr
