# Branches that trigger a build on commit
trigger:
- master
- master-vs-deps
- release/*
- features/*
- demos/*

# Branches that trigger builds on PR
pr:
- master
- master-vs-deps
- release/*
- features/*
- demos/*

stages:
- stage: Stage_1
  jobs:
  - job: Say_Hello
    pool:
      vmImage: windows-2019
    steps:
    - pwsh: echo 'Hello Stage1'
  - job: Get_Nonexistent_Item
    pool:
      vmImage: windows-2019
    steps:
    - pwsh: gi nonexistent.txt
  - job: List_Roslyn_PRs
    pool: server
    steps:
    - task: InvokeRESTAPI@1
      inputs:
        connectionType: 'connectedServiceName'
        serviceConnection: 'dotnet'
        method: 'GET'
        urlSuffix: /pulls
        waitForCompletion: false
        header: '{}'